# Generated by Django 4.2.2 on 2023-07-24 22:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0002_questioncommentmodel_questioncommentlikemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=51)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='questions_app.questioncategorymodel'),
        ),
    ]
