# Generated by Django 4.2.2 on 2023-07-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0006_alter_questioncommentmodel_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='questions_app.questioncategorymodel'),
            preserve_default=False,
        ),
    ]
